### ISSUE TITLE
Let the user know when an unreadable OTR message was received

### ISSUE THREAD

**Issue by BrianBlade** [siacs/Conversations#1021]
In rare cases an unreadable OTR message is received. Conversations will ignore such a message without informing the user. As far as I can tell, the sender is not informed about the failure either.

As stated at https://otr.cypherpunks.ca/Protocol-v3-4.0.0.html, right at the bottom of the page:

Receiving a Data Message
If msgstate is MSGSTATE_ENCRYPTED:
    Verify the information (MAC, keyids, ctr value, etc.) in the message.
    If the verification succeeds:
[...]
    Otherwise, inform the user that an unreadable encrypted message was received, and reply with an Error Message. 

I was not able to reproduce this issue when using two Conversations clients, however, if one party uses Chatsecure for example, you can provoke unreadable messages like so:
1.) Start OTR session
2.) Disconnect Chatsecure without logging off by enabling airplane mode for example (logout will destroy OTR session, but temporary disconnects dont)
3.) Wait until Conversations is notified about Chatsecure being offline (i.e., after stream management timeout)
4.) At this point Conversations discards the OTR session. Now connect Chatsecure again and send a message to Conversations. Logcat gives an "unreadable message received", but neither the user nor Chatsecure is informed about this event

From my POV Conversations is rigth to destroy OTR sessions as soon as one party is offline. Nonetheless, it would be great to inform the user and sender about the unreadable message. Especiallly so since temporary disconnects happen quite frequently in a mobile environment.

**Comment by interruptor** [comment]
You can also reproduce this by using two conversation clients and one party with two or more devices with different OTR keys:

1.) Party A: mobile connected to ejabberd; Party B: mobile and Tablet, both connected to ejabberd
2.) A's mobile communicates with B's mobile (OTR active), CC feature enabled
3.) mobile of B loses network connection or battery is empty
4.) messages are delivered to B's tablet and server thinks OK, delivered
5.) messages are lost because B's tablet conversations dropps it because of an unknown OTR session

Please correct me if i am wrong, but this seems to be a bit more complicated than just to implement a notification on undecryptable messages because B's tablet HAS TO drop die unencryptable messages while the communication from mobile to mobile works. Otherwise B would have a lot of garbage on his tablet for every message he or A sends to each other. You can reproduce this if you replace B's mobile with another XMPP Client, for example Pidgin - for some reason in this constellation B's tablet conversations does not drop the 'garbage' between A's mobile and B's Pidgin...

**Comment by iNPUTmice** [comment]
> You can reproduce this if you replace B's mobile with another XMPP Client, for example Pidgin - for some reason in this constellation B's tablet conversations does not drop the 'garbage' between A's mobile and B's Pidgin...

Proper clients disable carbon messages for OTR messages and send them only to one client. Pidgin doesn't. This way while chatting from Pidgin to a contact who is logged in with two Conversations will always result in one of the two Conversations showing garbage messages.


I will see what I can do about sending out error messages when receiving unreadable OTR messages (that are properly addressed and not those we are send out by pidgin or gajim on accident - bascially all those messages that are already printing a 'unreadable message received' debug message)

**Comment by Natanji** [comment]
I was always very annoyed by such OTR error messages. If I cannot decrypt the message, then I have to usually manually write to my contact "hey you sent me something, but OTR fucked up again, can you resend it please?". The way I see it, at least when both parties are online, this could be automated. In Pidgin, when I send someone a message when initiating an OTR conversation and the other party still has a different OTR session open, then they will reply with an OTR error message and the secure session will automatically be re-established, and my message resent.

I think it would be very useful to immediately request a resending of the OTR message if an unreadable message is received, instead of just displaying an error. We want this stuff to work easily, after all. Certainly we need to ensure that the OTR fingerprint isn't a foreign, unvereified one now because then this would trigger a resend to a potential MITM.

If the other person is no longer online, only *then* would I suggest displaying an error. But let's handle all other cases as good as we can without manual user interaction. OTR requires *way* too much manual interaction to be useful in its current state.

**Comment by BrianBlade** [comment]
>In Pidgin, when I send someone a message when initiating an OTR conversation and the other party still has a different OTR session open, then they will reply with an OTR error message and the secure session will automatically be re-established, and my message resent.

Thats what Chatsecure does as well. I played around a bit with error messages and ChatSecure resents unacked messages when receiving an OTR error message.
In OTRv3 there is even a flag to refresh the session when an OTR error message is encountered. Its also available in OTR4J as setErrorStartAKE().
I wonder if we could implement both, sending out error messages when receiving unreadable messages and parsing error messages to re-establish sessions and resend unsent messages?

**Comment by iNPUTmice** [comment]
As a first step I implemented notification of the sender.
Notification of the recipient might lead to very annoying error messages (and the recipient can't do anything with it besides notifying the sender which can also happen automatically.))
However there is currently no automatic action on the sending part besides marking the messages as failed. I first want to see how this works in the wild before I do anything like resetting the session or even resending the message.

**Comment by BrianBlade** [comment]
Hi,

I agree that it doesnt make much sense to inform the recipient. However, I am afraid this patch does not really fix the described issue. As far as I can see this is mainly due to two reasons:

1. The error is currently crossing protocol-layers, that is, Conversations sends out an XMPP error stanza according to RFC3920 when the error occured on the _OTR-Layer_ (i.e., inbound, being part of the "XMPP-payload"). This makes it impossible for Conversations (and likely for other clients as well) to identify the error as OTR-Error and act accordingly, because XMPP-Errors are treated differently.
  - An OTR-Error message must include: *?OTR Error:* to be identified as such. This string is currently missing if I am not mistaken
2. An OTR-Error is currently only send out if `messageFromAnotherInstanceReceived()` is called. 
  - The issue as described in the first post is different in that there is no valid OTR session and `unreadableMessageReceived()` is called. I am not even sure whether `messageFromAnotherInstanceReceived()` is ever called at all? From what I can see you do check the resourcepart of receiver and sender in `parseOtrChat()` and reset the session if necessary so it should hardly be possible to attempt decrypting messages for or from other instances. I might miss something but from my understanding the instance tag in OTRv3 messages is unecessary in XMPP anyway because fullJIDs/Resources are available to distinguish between different client-sessions.

I believe it makes sense to completely separate OTR-Errors from XMPP-Error messages. That is, let otr4j call `unreadableMessageReceived()` and respond with a simple plaintext message with the appropriate *?OTR Error:* indicator, possibly adding the *no-copy* hint and carbons' *private* flag. That would in consequence also make it necessary to parse incoming OTR messages for such errors and act accordingly (i.e., at least mark unacked OTR messages as failed).

Cheers and thanks for all your efforts!
