### ISSUE TITLE
Bug: Sending empty file

### ISSUE THREAD

**Issue by vijai1996** [siacs/Conversations#1126]
Tested to send out empty .txt file and I never succeeded in sending it. it says [code]did not find a primary candidate for ourself
received candidate error
could not find suitable candidate [/code] and the upload/download gets stuck at 0% indefinitely and never shows error too. The file extension becomes .null for the downloaded file. Also, if the text contains some data, the transfer is successful although I cannot open it. It says no app to handle the file. May be because the downloaded file extension is always .webp? Why couldnt it be of their original extension like .jpg, .png, .txt etc?

**Comment by iNPUTmice** [comment]
The bug concerning the 0 byte files is fixed. Thanks for reporting. I couldn't reproduce the .txt bug though. Files ending in .txt are send and received just fine.

> May be because the downloaded file extension is always .webp? Why couldnt it be of their original extension like .jpg, .png, .txt etc?

Conversations will keep the original file extension. (That is if you are on a more or less recent version)

**Comment by vijai1996** [comment]
@iNPUTmice I could still reproduce the bug after complete uninstallation of app, recompile from the newly synced source. Also, the extension are indeed .webp for all images and its always null for txt files irrespective of 0 bytes or contains data. The file names seem to be of some hash like string (eg: c8b675a5-d4c4-4262-b30d-d2dbc858e775.webp for image)
