### ISSUE TITLE
Can not send and receive messages at the same time

### ISSUE THREAD

**Issue by fuglede** [siacs/Conversations#1202]
Just bought the app but out of 5 attempts to start a conversation, so far none have succeeded.

In each test, the recipient would use Pidgin. I can communicate with them using Pidgin and/or ChatSecure without any problems.

Setup 1: Me using Pidgin (default priority), ChatSecure (priority 1), and Conversations.
Test: I initiated an OTR conversation and sent a message.
Result: OTR conversation started in my Pidgin client; OTR handshake (i.e. a garbled mess) echoed in Conversations. Recipient did not receive the message.

Setup 2:  Me using ChatSecure (priority 1) and Conversations (i.e. closed Pidgin)
Test: I initiated an OTR conversation and sent a message.
Result: No OTR handshake this time, reads as if message sent successfully. Recipient received the message and replied. I did not receive the reply. No errors/warnings

Setup 3: Running only Conversations (i.e. closed ChatSecure)
Test: I initiated an OTR conversation and sent a message.
Result: Recipient received the message and replied. I did not receive the reply. No errors/warnings.

Setup 4: Running only Conversations
Test: Closed the OTR conversation and sent a plain text message.
Result: Recipient did not receive the message. No errors/warnings.

Setup 5: Running only Conversations
Test: Repeated test 3.
Result: Same result as in 3.

**Comment by iNPUTmice** [comment]
Probably fixed in >=1.5.1 Have another look.

**Comment by fuglede** [comment]
@iNPUTmice Just tried the app again; this time version 1.5.2. Still doesn't work.

**Comment by iNPUTmice** [comment]
what server(s) are you using?

**Comment by fuglede** [comment]
jabber.dk

**Comment by fuglede** [comment]
Ran a new sequence of test, using those three clients, and asking the recipient if they recieve any messages:

* Test #1': Using only Pidgin. Working as intended.
* Test #2': Pidgin+Conversations. Sent from Pidgin. Message received. Conversations displays OTR handshake nonsense.
* Test #3': Pidgin+Conversations. Sent from Conversations. Message *not* received. Conversations displays OTR handshake.
* Test #4': Pidgin+Conversations+ChatSecure. From ChatSecure. Message receieved. Conversations displays handshake.
* Test #5': Conversations+ChatSecure. From Conversations. Message *not* received. Conversations displays padlock and string 'waiting'.
* Test #6': Conversations+ChatSecure. From ChatSecure, unencrypted. Working as intended.
* Test #7': Only Conversations. From Conversations. Message *not* received. Conversations displays padlock and 'waiting'.

I.e., in no cases did a message sent from Conversations end up where it was supposed to.

**Comment by fuglede** [comment]
Did a shorter test in 1.6.7; still doesn't work.
