### ISSUE TITLE
[1.3.1] Crash when creating new account

### ISSUE THREAD

**Issue by mhde** [siacs/Conversations#1204]
Try to register a new account on jabber.mhprojects.de with an ID and password of your choice, e.g.:
ID: foo@jabber.mhprojects.de
PW: 123

Conversations will display a message "failed to register" and keeps crashing from now on on start up.
Indeed no account will be created on the server.

The only solution so far is to reinstall the app.

Here's the stacktrace:
```
05-16 20:40:31.445  10514-10542/eu.siacs.conversations D/conversations﹕ test@jabber.mhprojects.de: error connecting account. try again in 36s for the 2 time
05-16 20:40:31.460  10514-10542/eu.siacs.conversations D/conversations﹕ test@jabber.mhprojects.de: disconnecting
05-16 20:40:31.480  10514-10542/eu.siacs.conversations W/dalvikvm﹕ threadid=15: thread exiting with uncaught exception (group=0x419dbce0)
05-16 20:40:31.527  10514-10514/eu.siacs.conversations I/Choreographer﹕ Skipped 32 frames!  The application may be doing too much work on its main thread.
05-16 20:40:31.562  10514-10542/eu.siacs.conversations E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-1688
    Process: eu.siacs.conversations, PID: 10514
    java.lang.NullPointerException
            at eu.siacs.conversations.xmpp.XmppConnection$2.onIqPacketReceived(XmppConnection.java:684)
            at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:478)
            at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:382)
            at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:564)
            at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:278)
            at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:218)
            at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:265)
            at java.lang.Thread.run(Thread.java:841)

```

**Comment by iNPUTmice** [comment]
This has been fixed in d74e8a8a0ea20258e9e0eefbea75f94b7559f9b7

**Comment by mhde** [comment]
Have you tested it with the latest development version? It has not been fixed yet!
Still crashes for 1.4.0-alpha.

**Comment by iNPUTmice** [comment]
ok should be fixed in HEAD

**Comment by mhde** [comment]
Thanks! The issue is resolved now.

**Comment by pravinkakde003** [comment]
Hello sir,
Thanks for great product.At creating account on my local opefire server with give null pointer exception.as mentioned by Mr.MHDE above.I update code as mentioned earlier but still it crash.

Logcat:

05-28 23:00:37.206: E/AndroidRuntime(14968): java.lang.NullPointerException
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection$2.onIqPacketReceived(XmppConnection.java:686)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:478)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:382)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:564)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:278)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:218)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:265)
05-28 23:00:37.206: E/AndroidRuntime(14968): 	at java.lang.Thread.run(Thread.java:856)
05-28 23:00:41.040: E/InputQueue-JNI(14968): channel '41f2e648 PopupWindow:41557190 (client)' ~ Publisher closed input channel or an error occurred.  events=0x8

stuck here..

**Comment by iNPUTmice** [comment]
@pravinkakde003 updated to what version?

**Comment by pravinkakde003** [comment]
latest development version..At the time of login it works perfect.gives null pointer at the time of account creation.As mentioned above 
https://github.com/siacs/Conversations/commit/d74e8a8a0ea20258e9e0eefbea75f94b7559f9b7 
i did changes..doesn't worked.

**Comment by iNPUTmice** [comment]
Have you applied d672d578c91f54e17b930c4a08d133095a863d52?

**Comment by pravinkakde003** [comment]
Applied as per you mentioned in comment..now app not get crashed but did not get registered.

Stacktrace:
05-29 11:56:20.921: I/dalvikvm(16164): Could not find method org.bouncycastle.util.BigIntegers.asUnsignedByteArray, referenced from method net.java.otr4j.crypto.OtrCryptoEngineImpl.verify
05-29 11:56:20.921: W/dalvikvm(16164): VFY: unable to resolve static method 19675: Lorg/bouncycastle/util/BigIntegers;.asUnsignedByteArray (Ljava/math/BigInteger;)[B
05-29 11:56:20.921: D/dalvikvm(16164): VFY: replacing opcode 0x71 at 0x0041
05-29 11:56:20.941: I/dalvikvm(16164): Could not find method org.bouncycastle.util.BigIntegers.asUnsignedByteArray, referenced from method net.java.otr4j.crypto.OtrCryptoEngineImpl.sign
05-29 11:56:20.941: W/dalvikvm(16164): VFY: unable to resolve static method 19675: Lorg/bouncycastle/util/BigIntegers;.asUnsignedByteArray (Ljava/math/BigInteger;)[B
05-29 11:56:20.941: D/dalvikvm(16164): VFY: replacing opcode 0x71 at 0x004d
05-29 11:56:21.422: D/conversations(16164): cb@192.168.0.105: connecting
05-29 11:56:21.532: D/conversations(16164): using dns server: 8.8.8.8 to look up 192.168.0.105
05-29 11:56:23.154: W/System.err(16164): java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-29 11:56:23.174: W/System.err(16164): 	at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:184)
05-29 11:56:23.174: W/System.err(16164): 	at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
05-29 11:56:23.174: W/System.err(16164): 	at de.duenndns.ssl.MemorizingTrustManager.checkCertTrusted(MemorizingTrustManager.java:418)
05-29 11:56:23.174: W/System.err(16164): 	at de.duenndns.ssl.MemorizingTrustManager.checkServerTrusted(MemorizingTrustManager.java:441)
05-29 11:56:23.174: W/System.err(16164): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:593)
05-29 11:56:23.174: W/System.err(16164): 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
05-29 11:56:23.174: W/System.err(16164): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
05-29 11:56:23.174: W/System.err(16164): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.getSession(OpenSSLSocketImpl.java:723)
05-29 11:56:23.174: W/System.err(16164): 	at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:555)
05-29 11:56:23.174: W/System.err(16164): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:278)
05-29 11:56:23.174: W/System.err(16164): 	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:218)
05-29 11:56:23.174: W/System.err(16164): 	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:265)
05-29 11:56:23.174: W/System.err(16164): 	at java.lang.Thread.run(Thread.java:856)
05-29 11:56:23.174: W/System.err(16164): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-29 11:56:23.174: W/System.err(16164): 	... 13 more
05-29 11:56:23.624: D/dalvikvm(16164): GC_CONCURRENT freed 720K, 9% free 10154K/11043K, paused 34ms+6ms
05-29 11:56:24.074: D/OpenGLRenderer(16164): Flushing caches (mode 0)
05-29 11:56:24.545: D/conversations(16164): app switched into background
05-29 11:56:25.396: D/conversations(16164): app switched into foreground
05-29 11:56:25.426: D/OpenGLRenderer(16164): Flushing caches (mode 0)
05-29 11:56:25.756: D/OpenGLRenderer(16164): Flushing caches (mode 0)
05-29 11:56:26.166: D/conversations(16164): app switched into background
05-29 11:56:26.647: D/conversations(16164): cb@192.168.0.105: TLS connection established
05-29 11:56:26.737: D/conversations(16164): app switched into foreground
05-29 11:56:27.017: D/OpenGLRenderer(16164): Flushing caches (mode 0)
05-29 11:56:27.087: D/conversations(16164): cb@192.168.0.105: error connecting account. try again in 32s for the 2 time
05-29 11:56:27.167: D/conversations(16164): cb@192.168.0.105: disconnecting

**Comment by iNPUTmice** [comment]
if you are unwilling to debug this yourself you are probably better of with
using the play store version on a public server.
