### ISSUE TITLE
Self-sent messages multiplying/endlessly repeating with Slack XMPP gateway

### ISSUE THREAD

**Issue by erno** [siacs/Conversations#1475]
We enabled XMPP gateway on our Slack and I used Conversations with it. Then some messages I wrote started repeating, they were getting sent over and over again to the Slack channel. The Slack support guys said they checked the logs and said the gateway hadn't been sending duplicate messages, and suspected it's a Conversations bug.

**Comment by iNPUTmice** [comment]
Just to be sure you are talking about conferences not 1:1 chats, right?

Also can I assume that messages you send remain marked as *sending...*?

**Comment by erno** [comment]
Yes, conferences.

I don't remember seeing them as "sending..." if that should be visible from the normal chat view.

**Comment by msjoberg** [comment]
I'm seeing this bug as well with the Slack gateway. For me it's conferences as well, and I'm seeing the "sending...", i.e. the message remains marked with that text below.

**Comment by iNPUTmice** [comment]
should be fixed in the current beta

**Comment by msjoberg** [comment]
Many thanks! I'm now running v1.7.0 from F-Droid in which I assume has the bug fix. It has indeed improved a lot, but I still see the repeating/multiplying messages. It may be a coincidence, but for me it appears to be triggered when I post a URL (which gets expanded in Slack with a an image attachment and an excerpt). Such a post still gets the "Sending..." text below, and get reposted over and over again.

**Comment by msjoberg** [comment]
OK, now it happened to me also with a non-url post. Anything I can do to help track this down? Should I open another issue, I don't seem to be able to re-open this issue.
