### ISSUE TITLE
Keep service in foreground checkbox not persisted when unchecked

### ISSUE THREAD

**Issue by S2-** [siacs/Conversations#2133]
#### General information

* **Version:** 1.14.9
* **Device:** xperia z5 compact
* **Android Version:** Android 6.0.1 Stock
* **Server name:** 31337.it
* **Server software:** prosody
* **Conversations source:** f-droid

#### Steps to reproduce
1. go to settings -> expert settings -> uncheck "keep service in forground"

#### Expected result

the notification on the toast should disappear and stay that way, but the notification comes back after some time, and the checkbox becomes checked again.

**Comment by iNPUTmice** [comment]
This is already fixed in HEAD.

**Comment by amenk** [comment]
Ah cool, when will it hit Google Play?

**Comment by participante0** [comment]
* **Version:** eg 1.15.0
* **Device:** Samsung Galaxy Trend Lite
* **Android Version:** Android 4.1.2
* **Conversations source:** F-Droid

The bug is still there. I don't know exactly how to reproduce it. But I kill Conversations at least once a day (I have the right to kill apps, please, don't tell me I shouldn't).

**Comment by andersruneson** [comment]
Once per day should not activate foreground service.

Anyway your are free to kill any app you like :)

Please note that this function exist to improve battery and data usage for
cases where the os kills Conversations and that happens rather frequently
(like several times per hour).

**Comment by andersruneson** [comment]
It would help yourself if you could provide a logcat when this happens (when you see that the persistent notification appears)

**Comment by participante0** [comment]
Now I know how to reproduce it. The app `360 Security` has an option to Boost phone (it doesn't kill the app). When Conversations is selected to be optimized, the notification goes back. But now I don't think it is a bug. I see it like a self defense technique of Conversations.

**Comment by amenk** [comment]
I would like to point out that this even seems to happen if no account is connected at all. That is why I deinstalled Conversations (at least temporarily) because of no chance to remove to notification.

**Comment by licaon-kter** [comment]
With 1.15.5 I'm not seeing any notification with keep foreground disabled.
