### ISSUE TITLE
Use XEP-0385 - SIMS when doing file upload

### ISSUE THREAD

**Issue by edhelas** [siacs/Conversations#2637]
Conversations currently use XEP-0066: Out of Band Data to embed a file in a message. However OOB doesn't give a lot of information on the file itself (even if some of them can be resolved by doing a HTTP HEAD request on the url).

The new XEP-0385: Stateless Inline Media Sharing (SIMS) provides all those missing information (name, picture resolution, thumbnails, hash, description…). Adding the support of SIMS in Conversations could help integrating more properly those file exchanges.

Movim already implement SIMS next to OOB so do not hesitate to test your implementation against it.
We are still doing a HTTP HEAD check on the URL to ensure that the size and MIME of the file embedded is the correct one.

**Comment by licaon-kter** [comment]
Would this fix #2440 ?

**Comment by edhelas** [comment]
@licaon-kter SIMS includes a tag `<name>` yes, it should fix this issue.

**Comment by splurched** [comment]
Kudos to movim people

**Comment by srgcdev** [comment]
I think its a nice feature to implement to finally have previous of images and videos before download it like others im programs do.

**Comment by iNPUTmice** [comment]
Currently not on our TODO list as it is unclear on how this work with E2EE.

And if this is primarily about thumbnails I'm not a big fan of requesting thumbnails with Bits of Binary. (But that discussion belongs to the list and not on this issue tracker)

**Comment by devurandom** [comment]
How is the download link passed to the recipient today? It seems that XEP-0363 does not specify this part? And how is that information encrypted currently?

XEP-0385's examples use `urn:xmpp:reference:0` for passing on the information about the download link, but that XEP does not register that namespace (it registers `urn:xmpp:sims:1` only). In fact https://xmpp.org/registrar/namespaces.html does not mention anyone having registered that namespace at all.

I assume the whole `<reference/>` element would have to be encrypted? As I understand XEP-0384, it only supports encrypting the `<body/>`, which is unstructured and plain text, so there is no chance of using it unmodified to encrypt other elements? Could XEP-0384 be extended to encrypt (arbitrary?) other elements?

**Comment by wiktor-k** [comment]
@devurandom you may be interested in Stanza Content Encryption. See the mailing list discussion at https://mail.jabber.org/pipermail/standards/2019-April/036002.html

**Comment by Ri0n** [comment]
I also interested in SIMS in Conversations.
I implemented sims in Psi but Conversations doesn't understand my audio messages. Probably doesn't understand sims at all.

**Comment by iNPUTmice** [comment]
I still don’t fully understand how SIMS works without references.
Do I just stick the `<media-sharing>` right in the `message`?
@Ri0n do you have an example xml snippet on how such an *audio message* looks like?

**Comment by Ri0n** [comment]
According to recent xsf discussions there is no way to use it w/o refereces.
And in fact I found it convenient. For example you can add all the references' html links into messgae.body on send and then recognize and remove them on receive. The top level reference has info where a particlar links starts and ends in the body.
So this way some compatibility with clients not supporting SIMS is preserved.

Currently Psi sends next xml. It's subect to change though
```xml
<?xml version="1.0" encoding="UTF-8"?>
<message to="xxx@server/Psi" type="groupchat" id="aacda">
   <body>some description http://host/uploaded/file</body>
   <reference xmlns="urn:xmpp:reference:0" begin="18" end="43" uri="http://host/uploaded/file" type="data">
      <media-sharing xmlns="urn:xmpp:sims:1">
         <file xmlns="urn:xmpp:jingle:apps:file-transfer:5">
            <hash xmlns="urn:xmpp:hashes:2" algo="sha-1">w0i4iWZW309YeUlm1O/x6IHlWHY=</hash>
            <media-type>audio/ogg</media-type>
            <name>6469d4f19d851bb6af827982a305bf4457cd5f59</name>
            <thumbnail xmlns="urn:xmpp:thumbs:1" width="64" height="64" mime-type="image/png" uri="cid:sha1+5d10f2e01688d42de0ed22a5153947b06833b6fe@bob.xmpp.org" />
            <histogram xmlns="urn:audio:histogram" coding="u8">12,11,10,10,11,11,9,9,10,9,10,9,10,11,28,44,41,58,96,49,17,22,65,65,44,43,22,44,53,36,52,59,47,27,20,29,27,25,14,11,16,41,22,16,24,45,17,67,88,199,141,31,14,36,67,76,63,31,14,11,53,47,24,53,27,16,63,75,58,70,47,29,15,16,57,90,53,66,50,56,132,63,44,48,50,42,39,60,94,65,34,27,41,43,32,25,12,10,11,12</histogram>
         </file>
         <sources>
            <reference xmlns="urn:xmpp:reference:0" uri="http://host/uploaded/file" type="data" />
         </sources>
      </media-sharing>
   </reference>
</message>
```
