### ISSUE TITLE
Messages that fail to decrypt are not shown at all in the UI

### ISSUE THREAD

**Issue by devurandom** [siacs/Conversations#2665]
#### General information

* **Version:** 1.21.0, both of us
* **Device:** Samsung Galaxy S4 Mini LTE (serranoltexx) on my end
* **Android Version:** Lineage OS 14.1 (Android 7.1.2) on my end
* **Server name:** self hosted on my end, remote end is on conversations.im
* **Server software:** Prosody 0.10 on my end
* **Installed server modules:** Stream Managment, CSI, MAM, and lots others on my end
* **Conversations source:** PlayStore, both of us

#### Steps to reproduce

1. Have someone migrate Conversations to another phone in the wrong way (using Google Backup, "completely automatic")
2. Receive OMEMO-encrypted messages from them
3. See nothing in your Conversations client

#### Expected result

My client should show the messages with an indication that we failed to decrypt them.

#### Actual result

Nothing.

#### Debug output

I see several instances of this message in the logs:
```
AxolotlService ($MY_JID): Failed to decrypt message from $REMOTE_JID: Error decrypting WhisperMessage InvalidMessageException: No valid sessions.
```

**Comment by devurandom** [comment]
#2227 describes a possible workaround / recovery from the mess: Resetting the OMEMO keys (`Settings > Expert > Security > Delete OMEMO identities`).

Finding this option was quite difficult. I first looked for that option in the account settings: I tried tapping and long pressing my OMEMO fingerprint in the account details, and also looked into the three-dots menu. Only after a while we found that it is not in the account settings, but in the general settings.

**Comment by jannic** [comment]
This has been fixed by bda95bc5711b2f1663c643f981839015795db8d1, I think.

**Comment by ou-li** [comment]
not fixed on my devices in 2.3.7+fcr 
 @devurandom : not acknowledging messages it cannot decrypt makes sense to me and helped me to spot the problem

**Comment by iNPUTmice** [comment]
Conversations 2.3.9 will display 'unable to decrypt' warnings and will also attempt to self heal broken sessions. Both features require your server to support `mam:2`.
