### ISSUE TITLE
Conversations 1.23.9 exhibits multiple issues with many avatar pictures

### ISSUE THREAD

**Issue by Olf0** [siacs/Conversations#2930]
#### General information

* **Version:** 1.23.9
* **Device:** Jolla 1 
* **Android Version:** AOSP 4.1.2 based Android runtime environment (AlienDalvik), API level 16
* **Server name:** various public ones
* **Server software:** ejabberd and prosody 
* **Installed server modules:** unknown
* **Conversations source:** F-Droid

#### Steps to reproduce

A. When trying to configure an existing, own account  (one out of three)
1. Configure new account, which already exists on a XMPP-server and has an avatar picture uploaded.
2. Upon connecting Conversations 1.23.9 crashes.
3. When restarting Conversations, the account is set up, but no avatar picture fetched.

B. When trying to freshly upload a missing avatar picture of ones own account
* When tapping on the empty (just the first letter of this account) avatar picture in "Manage accounts" --> \<specific account\> (which shows issue A.), Conversations 1.23.9 crashes.

C. When viewing other accounts under "Contacts"
* Many of them (> 50%, n ~ 10) show no avatar picture with Conversations 1.23.9

Conversations 1.23.8 (and all earlier versions) does not exhibit these issues (A., B. and C.) with exactly the same configuration and environment.
I failed to determine a common property of the failing avatar pictures (e.g. XMPP-server or used server software), but have not checked their size.

#### Debug output

As captured by Conversations; the output of cases A. and B. seems to be exactly the same (case C. does not crash, hence no log is automatically captured).
I can provide more sophisticated logs, if deemed helpful.

Version: 1.23.9
Last Update: 2018-04-01
SHA-1: 6b:57:64:ea:71:4b:fd:87:fa:74:bc:0d:9b:70:12:5c:ac:7a:ef:61

java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.siacs.conversations.legacy/eu.siacs.conversations.ui.PublishProfilePictureActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2066)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2091)
	at android.app.ActivityThread.access$600(ActivityThread.java:137)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4781)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.database.DatabaseUtils.findRowIdColumnIndex(DatabaseUtils.java:1395)
	at android.database.BulkCursorToCursorAdaptor.initialize(BulkCursorToCursorAdaptor.java:44)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:370)
	at android.content.ContentResolver.query(ContentResolver.java:370)
	at android.content.ContentResolver.query(ContentResolver.java:313)
	at eu.siacs.conversations.utils.PhoneHelper.getProfilePictureUri(PhoneHelper.java:92)
	at eu.siacs.conversations.ui.PublishProfilePictureActivity.onCreate(PublishProfilePictureActivity.java:126)
	at android.app.Activity.performCreate(Activity.java:5008)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2030)
	... 11 more

**Comment by iNPUTmice** [comment]
Fixed in 83f76c6b5e5cbbd91e1d6e0e5d0937888cc75497

**Comment by Olf0** [comment]
Thank you for fixing the sub-issues A. and B. per commit [83f76c6](https://github.com/siacs/Conversations/commit/83f76c6b5e5cbbd91e1d6e0e5d0937888cc75497).

But unfortunately, sub-issue C. still exists in **all** versions of Conversations newer than 1.23.8, i.e. 1.23.9/.10 *and* Conversations 2.
(I now also have a device under SailfishOS 2 with the last, Android 4.4 based AlienDalvik runtime environment.)

**Comment by licaon-kter** [comment]
Those avatars were set by what client? Server support for XEP-0398? Server software?

**Comment by Olf0** [comment]
Well, at least some of them were uploaded by Conversations (long ago).
Server software: Most chat partners are using jabber.de (prosody) or draugr.de / deshalbfrei.org / ubuntu-jabber.de / ubuntu-jabber.net / verdammung.org / xabber.de (ejabberd; supported XEPs: According to https://www.draugr.de/features/, those listed there and here: https://www.process-one.net/en/ejabberd/protocols/).

**Comment by Olf0** [comment]
Unfortunately https://xmpp.net/directory.phpdoes not reveal the software versions used, anymore.  Rhe same for the individual test at https://xmpp.net/result.php?domain=jabber.de&type=client

I will keep on trying to find something common in those accounts, of which the avatar pictures are failing to load.  (And still everything is working fine with Conversations 1.23.8.)

**Comment by licaon-kter** [comment]
You can use https://github.com/iNPUTmice/ComplianceTester to see the version.

**Comment by Olf0** [comment]
Sorry for the delay, I ran into (self inflicted) issues running the Java version of the compliance tester.
But it turns out that the results are already there:
- For *jabber.de*: https://compliance.conversations.im/server/jabber.de/
  Prosody 0.10.2, 94%
- For *draugr.de* (*deshalbfrei.org / ubuntu-jabber.de / ubuntu-jabber.net / verdammung.org / xabber.de*): https://compliance.conversations.im/server/draugr.de/
  ejabberd 18.04, 100%
