### ISSUE TITLE
Enhancement of search: Search activity feedback

### ISSUE THREAD

**Issue by Echolon** [siacs/Conversations#3233]
Hi,

so far, if you search for something, Conversations will search for it, and once it found something, it will be shown up.

However, if you start a search by pressing enter, the search starts but the user doesnt get any feedback that the search is runing.

I think this will give the user a feeling of no response. So I think, while a search is runing, there should be some visual feedback about it. (Blinking symbol

**Comment by licaon-kter** [comment]
This was fixed maybe?

**Comment by Echolon** [comment]
Hm, I just tested, the search is running but still doesnt tell you that it is running. I mean its not important, but inconsistent I think.

**Comment by licaon-kter** [comment]
If it didn't find anything you get the X picture, else it's the looking glass picture so it's running...you want what?

**Comment by Echolon** [comment]
Visual or informational feedback that the app actually is searching.
