### ISSUE TITLE
Cannot send images to chatsecure but can receive from it

### ISSUE THREAD

**Issue by schneekluth** [siacs/Conversations#3241]
Since 2.3.1+fcr (I think) I can no longer send images to chatsecure. If I send one chatsecure downloads the file but then shows a blank placeholder and an infinite loading sign. Strangely I can receive images from Chatsecure perfectly and also Conversations to Conversations works as expected. All participants use the same server: trashserver.net

**Comment by licaon-kter** [comment]
>  I tried downgrading but f-droid shows an error. It won't let me downgrade.

Yeah, I've edited my comment above ;)

**Comment by iNPUTmice** [comment]
Fixed in 2.3.4

**Comment by sijans** [comment]
It's still not working for me with 2.3.5. Works fine with 2.2.9.
Anyone else?

**Comment by schneekluth** [comment]
@sijans works fine since 2.3.4

**Comment by sijans** [comment]
Thanks, found it. Chatsecure hangs some time, when it receives images from an incompatible version.
